#ifndef  _CONSTANTS_H_
#define  _CONSTANTS_H_



#define VISIBLE_SIZE Director::getInstance()->getVisibleSize()
#define VISIBLE_ORIGIN Director::getInstance()->getVisibleOrigin()

//标签
#define BACKGROUND_TAG_1 1
#define BACKGROUND_TAG_2 2
#define HERO_TAG 3
#define HERO1_TAG 6
#define HERO2_TAG 9
#define LABEL_SCORE_TAG 10
#define UFO_TAG 4
#define MENU_TAG 11
#define ITEM_BOMB_TAG 12
#define LABEL_BOMB_TAG 13
#define ITEM_TOGGLE_TAG 14
#define LABEL_LIFE_TAG 16
#define LABEL_TIME_TAG 15
#define ITEM_LIFE_TAG 17


//ZORDER
#define BACKGROUND_ZORDER -1
#define DEFAULT_ZORDER 0
#define FOREGROUND_ZORDER 1
#define UI_ZORDER 99

//速度
#define BACKGROUND_SPEED 0.5f
#define BULLET_SPEED 6
#define SMALL_ENEMY_SPEED 4.5f
#define MIDDLE_ENEMY_SPEED 1.2f
#define BIG_ENEMY_SPEED 0.8f


//定时器相关
#define CREATE_BULLET_INTERVAL 0.2f
#define CREATE_SMALL_ENEMY_INTERVAL 1.4f
#define CREATE_MIDDLE_ENEMY_INTERVAL 6
#define CREATE_BIG_ENEMY_INTERVAL 25
#define CREATE_UFO_INTERVAL 10


#define CREATE_SMALL_ENEMY_DELAY 3
#define CREATE_MIDDLE_ENEMY_DELAY 15
#define CREATE_BIG_ENEMY_DELAY 45
#define CREATE_UFO_DELAY 10

//双子弹的发射次数
#define FULL_DOUBLE_BULLET_COUNT 30
#define DIVIDE_HERO_COUNT 100

//动画缓存键
#define HERO_FLY_ANIMATION "HEROFLY"
#define BIG_ENEMY_FLY_ANIMATION "BIGENEMYFLY"
#define MIDDLE_ENEMY_HIT_ANIMATION "MIDDLEENEMYHIT"
#define BIG_ENEMY_HIT_ANIMATION "BIGENEMYHIT"
#define SMALL_ENEMY_DOWN_ANIMATION "SMALLENEMYDOWN"
#define MIDDLE_ENEMY_DOWN_ANIMATION "MIDDLEENEMYDOWN"
#define BIG_ENEMY_DOWN_ANIMATION "BIGENEMYDOWN"
#define HERO_DOWN_ANIMATION "HERODOWN"


#define HIGH_SCORE_KEY "HIGHSCORE"



#define CREATE_ENEMY_GROUP_INTERVAL 10
#define CREATE_ENEMY_GROUP_DELAY 30


/*****************/

#define ENEMY1_TAG 6
#define ENEMY2_TAG 7
#define ENEMY3_TAG 8
#define ITEM_Hide_TAG 18

//血量
#define SMALL_ENEMY_BLOOD 1
#define MIDDLE_ENEMY_BLOOD 6
#define BIG_ENEMY_BLOOD 20


#endif // ! _CONSTANTS_H_ 
