#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

//界面
#define VISIBLE_SIZE Director::getInstance()->getVisibleSize()
#define VISIBLE_ORIGIN Director::getInstance()->getVisibleOrigin()


//标签
#define BACKGROUND_TAG_1 1  //注意合法标识符
#define BACKGROUND_TAG_2 2
#define HERO_TAG 3
#define UFO_TAG 4
#define LABEL_SCORE_TAG 10
#define MENU_TAG 11
#define ITEM_BOMB_TAG 12
#define LABEL_BOMB_TAG 13
#define TOGGLE_TAG 14


//ZORDER 遮挡
#define BACKGROUND_ZORDER -1
#define DEFAULT_ZORDER 0
#define FOERGROUND_ZORDER 1
#define UI_ZORDER 99

//速度
#define BACKGROUND_SPEED 0.5f
#define BULLET_SPEED 10
#define SMALL_ENEMY_SPEED -2.0f
#define MIDDELE_ENEMY_SPEED -1.0f
#define BIG_ENEMY_SPEED -0.8f
#define UFO_SPEED -2



//定时器相关
#define CREATE_BULLET_INTERVAL 0.1f
#define CREATE_SMALL_ENEMY_INTERVAL 5
#define CREATE_MIDDLE_ENEMY_INTERVAL 100
#define CREATE_BIG_ENEMY_INTERVAL 100
#define CREATE_UFO_INTERVAL 10 

#define CREATE_SMALL_ENEMY_DELAY  10
#define CREATE_MIDDLE_ENEMY_DELAY 30
#define CREATE_BIG_ENEMY_DELAY 30
#define CREATE_UFO_DELAY 5

//双子弹发射次数
#define FULL_DOUBLE_BULLET_COUNT 3

//动画缓存键
#define HERO_FLY_ANIMATION "HEROFLY"
#define BIG_ENEMY_FLY_ANIMATION "BIGENEMYFLY"
#define MIDDLE_ENEMY_HIT_ANIMATION "MIDDLEENEMYHIT"
#define BIG_ENEMY_HIT_ANIMATION "BIGENEMYHIT"
#define SMALL_ENEMY_DOWN_ANIMATION "SMALLENEMYDOWN"
#define MIDDLE_ENEMY_DOWN_ANIMATION "MIDDLEENEMYDOWN"
#define BIG_ENEMY_DOWN_ANIMATION "BIGENEMYDOWN"

#define HIGH_SCORE_KEY "HIGHSCORE"
#define HERO_DOWN_ANIMATION "HERODOWN"

#define CREATE_ENEMY_GROUP_INTERVAL 20
#define CREATE_ENEMY_GROUP_DELAY 5

#define CREATE_ENEMY_GROUP_1_INTERVAL 10
#define CREATE_ENEMY_GROUP_1_DELAY 10
#define CREATE_ENEMY_GROUP_2_INTERVAL 15
#define CREATE_ENEMY_GROUP_2_DELAY 10

#endif 